from tkinter import*
root=Tk()
root.geometry("600x400")
label=Label(root,text="Welcome to my app",font=("TimesNewRoman",16,"bold"),fg="blue",bg="yellow")
label2=Label(root,text="Python is fun",font=("Comicsans",14,"bold"),fg="Red",pady=10)
label3=Label(root,text="Tkinter makes it better",font=("Comicsans",12,"bold"),fg="Green",pady=10)
label4=Label(root,text="Let's build something cool!",font=("Comicsans",10,"bold"),fg="Orange",pady=10)
label.pack()
label2.pack()
label3.pack()
label4.pack()
label5=Label(root,text="Please wait",font=("TimesNewRoman",19,"bold"))
def start():
    label5.config(text="Now we will begin")
root.after(2000,start)
label5.pack(padx=10)
label6=Label(root,text="Top label")
label6.place(x=50,y=100)
label7=Label(root,text="Bottom label")
label7.place(x=150,y=50)
root.mainloop()